### ISSUE TITLE
Default queueable doesn't work

### ISSUE THREAD

**Issue by ruudboon** [eolant/vuetify-toast-snackbar#10]
Thank you for this great vuetify extension. It works great.
I only seeing one issue. 
I set the default option queueable to true when setting up the plugin (nuxt).
When firing notices they're not queued. When I directly add the queueable true option the calling method it works great. Other default options like position are working great.

**Comment by ruudboon** [comment]
👌

**Comment by eolant** [comment]
Thanks for the issue btw :)
