### ISSUE TITLE
Toast appearance: There's no close button on the toasts, text isn't centered

### ISSUE THREAD

**Issue by dcb99** [eolant/vuetify-toast-snackbar#11]
When the toast notification is displayed, there's no indication to  the user that they can close it. It would be helpful (and look better IMO) if there was an "X" or close button at the end of the toast. It would also be nice to be able to center the text in the toast.

**Comment by eolant** [comment]
@dcb99 Thanks for your thoughts, sorry it took me so long to look into this. I can see where "X" close button can make sense. I'll work on implementing this feature. Text alignment also can make sense but probably only if there are no icons or no close button. I think case of aligning text might be too narrow and custom to implement and it'll be easier for those who want to change the style of the toast to do it using css.
