### ISSUE TITLE
Cannot find module '../node_modules/style-inject/dist/style-inject.es.js

### ISSUE THREAD

**Issue by catelina95** [eolant/vuetify-toast-snackbar#12]
Cannot find module '../node_modules/style-inject/dist/style-inject.es.js

**Comment by eolant** [comment]
I can't replicate this issue, probably related to how you bundle your assets. I'd suggest trying to install style inject manually `npm install style-inject`.

**Comment by catelina95** [comment]
![image](https://user-images.githubusercontent.com/16163090/59997738-565e7a00-9690-11e9-8110-1ae997590679.png)
![image](https://user-images.githubusercontent.com/16163090/59997750-5eb6b500-9690-11e9-8dae-b1e1a491c6f1.png)
`npm install style-inject` can't solve this problem.

**Comment by catelina95** [comment]
哈哈, 谢谢啦.. 我解决这个问题了... 我用你的项目里的源文件解决的. thank you very much..☺️

**Comment by aldarund** [comment]
@eolant in your dist  you are referencing style-inject while there no peer dep for it. And its referenced really wrong way e.g.
../node_modules/styles_inject - which would end up into non existing path. So your dist is broken..

**Comment by eolant** [comment]
@aldarund Looks like rollup postcss and bili doing something weird. I was able to find and import statement in [rollup-plugin-postcss](https://github.com/egoist/rollup-plugin-postcss/blob/master/src/postcss-loader.js) but i'm not sure yet how to resolve this.

---

Actually there is a way to bundle modules in all builds. I think I will go with this option.
