### ISSUE TITLE
compoent not register

### ISSUE THREAD

**Issue by vasan057** [eolant/vuetify-toast-snackbar#13]
I am getting  app.js:142552 [Vue warn]: Unknown custom element: <v-snackbar> - did you register the component correctly?

**Comment by JafarAkhondali** [comment]
I have the same problem

**Comment by eolant** [comment]
Can anyone provide more information on how to reproduce this issue?

**Comment by JafarAkhondali** [comment]
> Can anyone provide more information on how to reproduce this issue?

I did nothing special! just used your config, and tried to call the module:
`this.$toast.info('Info toast')`
Here is the result:
![image](https://user-images.githubusercontent.com/11364402/61622475-1a680600-ac8a-11e9-817a-461550864937.png)

And there is no snackbar

**Comment by eolant** [comment]
No mean what kind of environment is it? And what init code is?
Please not that if you're using vue-loader you have to specify `VSnackbar`, `VBtn`, `VIcon` as global components. Refer to [Nuxt.js set up](https://github.com/eolant/vuetify-toast-snackbar).

**Comment by JafarAkhondali** [comment]
I'm using this template:
https://github.com/tookit/vue-material-admin

Its not Nuxt.js. Init code is the one you provided

**Comment by JafarAkhondali** [comment]
Specified global components as mentioned in Nuxt.js, and it worked. But I'm not using Nuxt, so why should they registered globally? Perhaps better to fix it or mention this in the docs

**Comment by eolant** [comment]
Fair point, I'll add vue loader next to Nuxt.js. I believe original issue is the same and it's safe to close this.
