### ISSUE TITLE
Replace the "flat" prop of close button in "text"

### ISSUE THREAD

**Issue by lorro** [eolant/vuetify-toast-snackbar#18]
This is also a change from Vuetify1 to Vuetify2.
The "flat" prop of VBtn has been renamed to "text".

> [Vuetify] [BREAKING] 'flat' has been removed, use 'text' instead. For more information, see the upgrade guide https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0#user-content-upgrade-guide

Also the prop 'auto-height' has been removed

> [Vuetify] [REMOVED] 'auto-height' has been removed. You can safely omit it.

**Comment by eolant** [comment]
@lorro thanks!
I double checked the docs and it looks like `text` property isn't required as `icon` already does it.
> Designates the button as icon - round and flat

**Comment by hamzamihaidanielx** [comment]
And, when can we expect a fix for this? I'm using it too...
