### ISSUE TITLE
update text in real time

### ISSUE THREAD

**Issue by pedrazadixon** [eolant/vuetify-toast-snackbar#20]
Any way to update a part of message string in real time? 
I want notification (toast) that update a download progress from axios.
¿Any idea?

**Comment by eolant** [comment]
As of now, it's not possible. But I played around a bit and there is a way to do it by exposing currently displayed toast component using a method:
```js
this.$toast.info(null, { timeout: 20000 })
setInterval(() => {
  const cmp = this.$toast.getCmp()
  if (cmp) {
    cmp.message = new Date()
  }
}, 1000)
```
Will this work in your use case?

P.S.: don't mind infinite interval :)

**Comment by pedrazadixon** [comment]
I try this but getCmp() is not defined.

**Comment by eolant** [comment]
@pedrazadixon, yes, because I haven't implemented it yet, just asking if this kind of workflow will work for your case?

**Comment by pedrazadixon** [comment]
Ahhh ok. Of course!
It's just what I need

Thank you in advance for your answers.
