### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by 5E1EMENT** [eolant/vuetify-toast-snackbar#22]
Hello. I want to use your plugin, but i have an error in my console when i emit it  like:
 `this.$toast('Default toast').`
I installed it correct in main.js: 
`import VuetifyToast from 'vuetify-toast-snackbar'`
`Vue.use(VuetifyToast)`

There is an error: `Error in v-on handler: "TypeError: this.$toast is not a function"`
I tried to emit this toast from my component by click. Why this error happens?

**Comment by eolant** [comment]
@5E1EMENT `this` isn't available in template context. Use `$toast` or move your call into method.

**Comment by 5E1EMENT** [comment]
I call this.$toast('Default toast') from method

**Comment by eolant** [comment]
@5E1EMENT can you please recreate your set up in the [sandbox](https://codesandbox.io/s/vuetify-playground-132jh)? I don't have enough information to help you.

**Comment by 5E1EMENT** [comment]
I placed the code in the dialog file: https://codesandbox.io/s/vuetify-playground-mu582

**Comment by eolant** [comment]
@5E1EMENT Oh, you are calling methods yourself without binding them to correct context (Vue.js does it for you normally). Try [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call):
```js
this.$options.methods[item.method].call(this, router)
```
