### ISSUE TITLE
Add vuetify loader in README

### ISSUE THREAD

**Issue by mattLLVW** [eolant/vuetify-toast-snackbar#25]
It's a bit unclear how to load  vuetify-toast-snackbar with vuetify loader.

I found [this](https://github.com/eolant/vuetify-toast-snackbar/issues/6) closed issue which helped.

It would be helpful to add specifically how to load this with vuetify loader to the README

**Comment by eolant** [comment]
@mattLLVW but it is in Readme? Under title "Vue loader (e.g. Nuxt.js)" or is this instruction not clear enough?

**Comment by mattLLVW** [comment]
I didn't get that the vue loader was indeed the vuetify loader.
