### ISSUE TITLE
OnClick Handler

### ISSUE THREAD

**Issue by jappyjan** [eolant/vuetify-toast-snackbar#26]
I'm using your toast component for a chat inside my application and it would be nice if you could add the option of adding a clickable button (call to action) into the toast.

to open the mentioned chat for example.

**Comment by eolant** [comment]
@jappyjan great idea, I'll cook something up soon.

**Comment by eolant** [comment]
@jappyjan check out new `slot` option I've added, you can use `this.$createElement` to create links buttons and other components.

**Comment by jappyjan** [comment]
thanks a lot! this solved it! great work!
