### ISSUE TITLE
Missing method for close all "$toasts"

### ISSUE THREAD

**Issue by julpat** [eolant/vuetify-toast-snackbar#29]
When I have group of $toasts (`error` form validation messages), then fix the form and submit, I want to close all current $toasts and show new one (maybe a `success` message if I got lucky).

So something like `this.$toast.closeAll()`.
(And `this.$toast.getQueue)` could be also nice to have accessable 😇 )

Current behavior: new `success` message appears at the end of queue and user does not see it until he close manualy all the `error` $toasts.

Quick fix could be show LIFO (last in - first out) order instead of current FIFO (first in - first out).

**Comment by eolant** [comment]
@julpat great idea, I'll do that as soon as I have time :) thinking about method `clearQueue` which will clear all queued toasts.
