### ISSUE TITLE
Inject in Nuxt context

### ISSUE THREAD

**Issue by votintsev** [eolant/vuetify-toast-snackbar#5]
Hello.

Do you have idea how I can inject you package in nuxt context. I tried created plugin like:

```js
import Vue from 'vue'
import VuetifyToast from 'vuetify-toast-snackbar'

Vue.use(VuetifyToast, {
  x: 'right',
  y: 'top',
  color: 'info',
  icon: 'info',
  timeout: 3000,
  dismissable: true,
  autoHeight: false,
  multiLine: false,
  vertical: false,
  shorts: {
    custom: {
      color: 'purple',
    },
  },
  property: '$toasted',
})

export default function (ctx, inject) {
  inject('toast', Vue.prototype.$toasted)
}
```

inspired: [https://github.com/nuxt-community/modules/blob/master/packages/toast/plugin.js](https://github.com/nuxt-community/modules/blob/master/packages/toast/plugin.js)

But it doesn't work :(

**Comment by eolant** [comment]
Hi, sorry took me some time to take a look at it. It's pretty simple, put this in `plugins/vuetify.js`:
```js
import Vue from 'vue'
import Vuetify, { VSnackbar } from 'vuetify/lib'
import VuetifyToast from 'vuetify-toast-snackbar'

Vue.use(Vuetify, {
  components: {
    VSnackbar
  }
})

Vue.use(VuetifyToast)
```

**Comment by votintsev** [comment]
Hi, @eolant . Thanks for the answer. But you provide solution not for my question. I need [Combined inject](https://nuxtjs.org/guide/plugins#combined-inject).

**Comment by eolant** [comment]
Sorry @votintsev , I misunderstood. Please try example from nuxt documentation:
```js
export default ({ app }, inject) => {
  inject('toast', Vue.prototype.$toasted)
}
```
It works for me and I'm able to call toast from store context too. Note that you'll still need my previous answer to define `VSnackbar` component. Just add `export` at the end of the file.
